# Generated by Django 6.0.7 on 2026-07-14 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nicho', models.CharField(choices=[('FOTO', 'Fotógrafo'), ('TRAN', 'Trancista'), ('BARB', 'Barbeiro'), ('EVEN', 'Produtor de Eventos')], max_length=4)),
                ('whatsapp', models.CharField(help_text='Ex: 5584999999999', max_length=15)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('disponivel', models.BooleanField(default=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='agenda.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='agenda.profissional')),
            ],
        ),
    ]
