# Generated by Django 6.0.7 on 2026-07-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='foto',
            field=models.ImageField(blank=True, help_text='Suba a foto do profissional', null=True, upload_to='profissionais/'),
        ),
    ]
