# Generated by Django 6.0.7 on 2026-07-15 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_profissional_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='nicho',
            field=models.CharField(choices=[('FOTO', 'Fotógrafo'), ('TRAN', 'Trancista'), ('BARB', 'Barbeiro'), ('EVEN', 'Produtor de Eventos'), ('NAIL', 'Nail Designer'), ('SERR', 'Trio Pé de Serra')], max_length=4),
        ),
    ]
